name: fetching-sources
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: ./update
      - run: "git config user.email haruki7049@users.noreply.github.com"
      - run: "git config user.name cpython-overlay"
      - run: "git add -A"
      - run: "git commit -m 'ci: Update sources.json' | true"
      - run: "git push -u origin main"
